databaseChangeLog:
  - changeSet:
      id: central-001-create-users-roles
      author: copilot
      changes:
        - createTable:
            tableName: central_users
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
                    primaryKeyName: pk_central_users
              - column:
                  name: username
                  type: VARCHAR(150)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: uq_central_users_username
              - column:
                  name: password
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: enabled
                  type: BOOLEAN
                  defaultValueBoolean: true
              - column:
                  name: created_at
                  type: TIMESTAMP
              - column:
                  name: updated_at
                  type: TIMESTAMP
        - createTable:
            tableName: central_roles
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
                    primaryKeyName: pk_central_roles
              - column:
                  name: name
                  type: VARCHAR(100)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: uq_central_roles_name
              - column:
                  name: created_at
                  type: TIMESTAMP
              - column:
                  name: updated_at
                  type: TIMESTAMP
        - createTable:
            tableName: central_permissions
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
                    primaryKeyName: pk_central_permissions
              - column:
                  name: name
                  type: VARCHAR(150)
                  constraints:
                    nullable: false
                    unique: true
                    uniqueConstraintName: uq_central_permissions_name
              - column:
                  name: created_at
                  type: TIMESTAMP
              - column:
                  name: updated_at
                  type: TIMESTAMP
        - createTable:
            tableName: central_role_permissions
            columns:
              - column:
                  name: role_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: permission_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - addUniqueConstraint:
                  tableName: central_role_permissions
                  columnNames: role_id,permission_id
                  constraintName: uq_central_role_permissions
        - createTable:
            tableName: central_user_roles
            columns:
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: role_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - addUniqueConstraint:
                  tableName: central_user_roles
                  columnNames: user_id,role_id
                  constraintName: uq_central_user_roles
