spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oli_cms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
server:
  port: 8080
jwt:
  secret: "your_jwt_secret_key"
  expiration: 86400
