name: Backend CI

on:
  push:
    branches-ignore:
      - master
      - release/**
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches:
      - master
      - release/**
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lint and Test (backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint (Spotless check via Docker stage)
        run: make -C backend lint

      - name: Test (via Docker stage; collects reports)
        run: make -C backend test

      - name: Upload JUnit and Jacoco reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-artifacts
          path: |
            backend/reports/junit
            backend/reports/jacoco
          if-no-files-found: ignore
