name: Backend CI

on:
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    name: Lint and Test (backend)
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint (Spotless check via Docker stage)
        run: make -C backend lint

      - name: Test (via Docker stage; collects reports)
        run: make -C backend test

      - name: Upload Pages artifact (from test/)
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          name: backend-test-reports
          path: |
            reports/backend
            reports/index.html
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
