name: Frontend CI

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-and-test:
    name: Lint and Test (frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint (Docker stage via Makefile)
        run: make -C frontend lint

      - name: Test (Docker stage via Makefile)
        run: make -C frontend test

      - name: Upload Jest coverage and junit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-artifacts
          path: |
            frontend/coverage
            frontend/coverage/junit.xml
          if-no-files-found: ignore
