name: Frontend CI

on:
  push:
    branches-ignore:
      - master
      - release/**
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  lint-and-test:
    name: Lint and Test (frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Lint
        run: npm run lint --silent

      - name: Test
        run: npm test --silent -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT: coverage/junit.xml

      - name: Upload Jest coverage and junit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-artifacts
          path: |
            frontend/coverage
            frontend/coverage/junit.xml
          if-no-files-found: ignore
